// widget/src/widgets/comments/CommentItem.tsx
import { useState } from 'react'
import ReplyItem from './ReplyItem'
import { useToast } from './useToast'
import type { Comment, Reply, NewComment } from './types'

interface Props {
  comment: Comment
  widgetKey: string
  pageUrl: string
  isPinned: boolean
}

export default function CommentItem({ comment, widgetKey, pageUrl, isPinned }: Props) {
  const [replies, setReplies] = useState<Reply[]>(comment.replies)
  const [expanded, setExpanded] = useState(false)
  const [showReplies, setShowReplies] = useState(false)
  const [replyOpen, setReplyOpen] = useState(false)
  const [replyBody, setReplyBody] = useState('')
  const { message, fading, show } = useToast()

  const LIMIT = 1000
  const MAX_LINES = 3
  const lines = comment.body.split('\n')
  const isLong = comment.body.length > LIMIT || lines.length > MAX_LINES

  let displayBody: string
  if (expanded || !isLong) {
    displayBody = comment.body
  } else {
    displayBody = lines.length > MAX_LINES
      ? lines.slice(0, MAX_LINES).join('\n') + '...'
      : comment.body.slice(0, LIMIT) + '...'
  }

  const handleReplyPosted = (reply: Reply) => {
    setReplies(prev => [...prev, reply])
    setShowReplies(true)
  }

  const postReply = async () => {
    if (!replyBody.trim()) return

    const res = await fetch(`${import.meta.env.VITE_API_URL}/public/comments`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        widget_key: widgetKey,
        page_url: pageUrl,
        body: replyBody,
        parent_id: comment.id,
      }),
    })

    const data: NewComment = await res.json()

    if (!res.ok) {
      show((data as any).error || 'Failed to post reply')
      return
    }

    setReplyBody('')
    setReplyOpen(false)

    if (data.status === 'approved') {
      setReplies(prev => [...prev, {
        id: data.id,
        body: data.body,
        createdAt: data.createdAt,
        quotedId: null,
        quoted: null,
        isOwnerReply: false,
      }])
      setShowReplies(true)
      show('Reply posted!')
    } else {
      show('Your reply has been submitted and is awaiting approval.')
    }
  }

  return (
    <div className={`comment ${isPinned ? 'comment-pinned' : ''}`}>
      <div style={{ display: 'flex', gap: '6px', marginBottom: isPinned || comment.isOwnerReply ? '6px' : '0' }}>
        {isPinned && <span className="pinned-badge">Pinned</span>}
        {comment.isOwnerReply && <span className="owner-badge">Site owner</span>}
      </div>
      <p className="comment-body">{displayBody}</p>
      {isLong && (
        <button className="btn-show-more" onClick={() => setExpanded(!expanded)}>
          {expanded ? 'Show less' : 'Show more'}
        </button>
      )}
      <div className="comment-meta">
        <span className="comment-time">{new Date(comment.createdAt).toLocaleString()}</span>
        <div className="comment-actions">
          <button className="btn-reply" onClick={() => setReplyOpen(!replyOpen)}>
            {replyOpen ? 'Cancel' : 'Reply'}
          </button>
        </div>
      </div>
      {replyOpen && (
        <div className="reply-input-area">
          <textarea
            value={replyBody}
            onChange={e => setReplyBody(e.target.value)}
            maxLength={1000}
            placeholder="Add a reply..."
            autoFocus
          />
          {message && (
            <div className={`toast ${fading ? 'toast-fade-out' : ''}`}>{message}</div>
          )}
          <div className="reply-actions">
            <span className="char-count">{replyBody.length}/1000</span>
            <div style={{ display: 'flex', gap: '8px' }}>
              <button className="btn-cancel" onClick={() => { setReplyOpen(false); setReplyBody('') }}>
                Cancel
              </button>
              <button className="btn-post-reply" onClick={postReply} disabled={!replyBody.trim()}>
                Reply
              </button>
            </div>
          </div>
        </div>
      )}
      {replies.length > 0 && (
        <>
          <button className="btn-show-replies" onClick={() => setShowReplies(!showReplies)}>
            {showReplies ? 'Hide replies' : `Show ${replies.length} ${replies.length === 1 ? 'reply' : 'replies'}`}
          </button>
          {showReplies && (
            <div className="replies">
              {replies.map(r => (
                <ReplyItem
                  key={r.id}
                  reply={r}
                  widgetKey={widgetKey}
                  pageUrl={pageUrl}
                  parentId={comment.id}
                  onReplyPosted={handleReplyPosted}
                />
              ))}
            </div>
          )}
        </>
      )}
    </div>
  )
}

// widget-svelte/src/widgets/comments/renderer/CommentItem.svelte
<script lang="ts">
  import ReplyItem from './ReplyItem.svelte'
  import type { Comment, Reply, DeleteCommentFn, PostReplyFn, DeleteReplyFn } from '../../../types'
  import { Toast } from '../toast.svelte'
  import { timeAgo } from '../timeago'
  import { getTruncatedBody } from '../truncate'

  export interface Props {
    comment: Comment
    widgetKey: string
    isPinned: boolean
    ownDisplayId: string | null
    onDeleted: (commentId: string) => void
    onDeleteComment: DeleteCommentFn
    onPostReply: PostReplyFn
    onDeleteReply: DeleteReplyFn
  }

  let { comment, widgetKey, isPinned, ownDisplayId, onDeleted, onDeleteComment, onPostReply, onDeleteReply }: Props = $props()

  let replies = $state<Reply[]>([])
  let expanded = $state(false)
  let showReplies = $state(false)
  let replyOpen = $state(false)
  let replyBody = $state('')
  let replyAuthorName = $state('')
  const toast = new Toast()

  const STORAGE_KEY = $derived(`plopkit_author_${widgetKey}`)
  const REPLIES_PAGE_SIZE = 20
  let visibleReplyCount = $state(REPLIES_PAGE_SIZE)

  const truncated = $derived(getTruncatedBody(comment.body, expanded))
  const visibleReplies = $derived(replies.slice(0, visibleReplyCount))
  const hasMoreReplies = $derived(replies.length > visibleReplyCount)

  const isOwn = $derived(
    !!ownDisplayId && comment.commenterDisplayId === ownDisplayId && !comment.isOwnerReply
  )

  $effect(() => {
    replies = [...comment.replies]
  })

  function loadSavedName() {
    try { return localStorage.getItem(STORAGE_KEY) ?? '' } catch { return '' }
  }

  function saveName(name: string) {
    try {
      if (name.trim()) localStorage.setItem(STORAGE_KEY, name.trim())
      else localStorage.removeItem(STORAGE_KEY)
    } catch {}
  }

  function openReply() {
    replyAuthorName = loadSavedName()
    replyOpen = true
  }

  function showMoreReplies() {
    visibleReplyCount += REPLIES_PAGE_SIZE
  }

  function handleReplyPosted(reply: Reply) {
    replies = [...replies, reply]
    showReplies = true
  }

  function handleReplyDeleted(replyId: string) {
    replies = replies.filter(r => r.id !== replyId)
  }

  async function deleteComment() {
    try {
      await onDeleteComment(comment.id)
      onDeleted(comment.id)
    } catch (err: any) {
      toast.show(err?.message || 'Failed to delete comment')
    }
  }

  async function postReply() {
    if (!replyBody.trim()) return
    const nameToSend = replyAuthorName.trim() || ''
    try {
      const newReply = await onPostReply(comment.id, replyBody, nameToSend)
      saveName(nameToSend)
      replyBody = ''
      replyOpen = false
      showReplies = true
      replies = [...replies, newReply]
      toast.show(newReply.status === 'approved'
        ? 'Reply posted!'
        : 'Your reply has been submitted and is awaiting approval.')
    } catch (err: any) {
      toast.show(err?.message || 'Failed to post reply')
    }
  }
</script>

<div class="comment {isPinned ? 'comment-pinned' : ''}" id={`comment-${comment.id}`}>
  {#if isPinned || comment.isOwnerReply}
    <div style="display:flex;gap:6px;margin-bottom:6px">
      {#if isPinned}<span class="pinned-badge">Pinned</span>{/if}
      {#if comment.isOwnerReply}<span class="owner-badge">Owner</span>{/if}
    </div>
  {/if}
  <span class="comment-author">{comment.authorName}</span>
  {#if comment.commenterDisplayId}<span class="commenter-id">#{comment.commenterDisplayId}</span>{/if}
  <p class="comment-body">{truncated.displayBody}</p>
  {#if truncated.isLong}
    <button class="btn-show-more" onclick={() => expanded = !expanded}>
      {expanded ? 'Show less' : 'Show more'}
    </button>
  {/if}
  <div class="comment-meta">
    <span class="comment-time">{timeAgo(comment.createdAt)}</span>
    <div class="comment-actions">
      {#if isOwn}<button class="btn-delete-own" onclick={deleteComment}>Delete</button>{/if}
      <button class="btn-reply" onclick={() => replyOpen ? (replyOpen = false) : openReply()}>
        {replyOpen ? 'Cancel' : 'Reply'}
      </button>
    </div>
  </div>
  {#if replyOpen}
    <div class="reply-input-area">
      <input class="author-input" bind:value={replyAuthorName} maxlength={30} placeholder="Name (optional)" />
      <textarea bind:value={replyBody} maxlength={2500} placeholder="Add a reply..."></textarea>
      <div class="reply-actions">
        <span class="char-count">{replyBody.length}/2500</span>
        <div style="display:flex;gap:8px">
          <button class="btn-cancel" onclick={() => { replyOpen = false; replyBody = '' }}>Cancel</button>
          <button class="btn-post-reply" onclick={postReply} disabled={!replyBody.trim()}>Reply</button>
        </div>
      </div>
    </div>
  {/if}
  {#if toast.message}
    <div class="toast {toast.fading ? 'toast-fade-out' : ''}">{toast.message}</div>
  {/if}
  {#if replies.length > 0}
    <button class="btn-show-replies" onclick={() => showReplies = !showReplies}>
      {showReplies ? 'Hide replies' : `Show ${replies.length} ${replies.length === 1 ? 'reply' : 'replies'}`}
    </button>
    {#if showReplies}
      <div class="replies">
        {#each visibleReplies as r (r.id)}
          <ReplyItem
            reply={r}
            {widgetKey}
            parentId={comment.id}
            {ownDisplayId}
            {onPostReply}
            {onDeleteReply}
            onReplyPosted={handleReplyPosted}
            onDeleted={handleReplyDeleted}
          />
        {/each}
        {#if hasMoreReplies}
          <button class="btn-show-replies" onclick={showMoreReplies}>
            Show {Math.min(REPLIES_PAGE_SIZE, replies.length - visibleReplyCount)} more {replies.length - visibleReplyCount === 1 ? 'reply' : 'replies'}
          </button>
        {/if}
      </div>
    {/if}
  {/if}
</div>
