// widget-svelte/src/widgets/comments/index.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import CommentItem from './CommentItem.svelte'
  import type { Comment, CommentsResponse, NewComment, BaseWidgetProps } from '../../types'
  import { Toast } from './toast.svelte'
  import styles from './comments.css?inline'

  let { widgetKey, pageUrl, shadowRoot }: BaseWidgetProps = $props()

  let comments = $state<Comment[]>([])
  let hasMore = $state(false)
  let loading = $state(false)
  let body = $state('')
  let total = $state(0)
  let pinnedCommentId = $state<string | null>(null)
  const toast = new Toast()

  async function fetchComments(cursor?: string) {
    loading = true
    const url = `${import.meta.env.VITE_API_URL}/public/comments?widget_key=${widgetKey}&page_url=${encodeURIComponent(pageUrl)}${cursor ? `&cursor=${cursor}` : ''}`
    const data: CommentsResponse = await fetch(url).then(r => r.json())
    comments = cursor ? [...comments, ...data.comments] : data.comments
    hasMore = data.hasMore
    total = data.total ?? (cursor ? total : data.comments.length)
    if (!cursor) pinnedCommentId = data.pinnedCommentId
    loading = false
  }

  function loadMore() {
    const last = comments[comments.length - 1]
    if (last) fetchComments(last.id)
  }

  async function postComment() {
    if (!body.trim()) return

    const res = await fetch(`${import.meta.env.VITE_API_URL}/public/comments`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ widget_key: widgetKey, page_url: pageUrl, body }),
    })

    const data: NewComment = await res.json()

    if (!res.ok) {
      toast.show((data as any).error || 'Failed to post comment')
      return
    }

    body = ''

    if (data.status === 'approved') {
      comments = [{ ...data, replies: [] }, ...comments]
      total += 1
      toast.show('Comment posted!')
    } else {
      toast.show('Your comment has been submitted and is awaiting approval.')
    }
  }

  onMount(() => {
    const styleEl = document.createElement('style')
    styleEl.textContent = styles
    shadowRoot.insertBefore(styleEl, shadowRoot.firstChild)
    fetchComments()
  })
</script>

<div class="widget">
  <h3>{total} {total === 1 ? 'Comment' : 'Comments'}</h3>
  <div class="input-area">
    <textarea
      bind:value={body}
      maxlength={1000}
      placeholder="Add a comment..."
    ></textarea>
    <div class="input-actions">
      <span class="char-count">{body.length}/1000</span>
      <button class="btn-post" onclick={postComment} disabled={!body.trim()}>
        Post
      </button>
    </div>
  </div>
  {#if toast.message}
    <div class="toast {toast.fading ? 'toast-fade-out' : ''}">{toast.message}</div>
  {/if}
  <div class="comments-list">
    {#if comments.length === 0 && !loading}
      <p class="empty">No comments yet. Be the first!</p>
    {/if}
    {#each comments as c (c.id)}
      <CommentItem
        comment={c}
        {widgetKey}
        {pageUrl}
        isPinned={pinnedCommentId === c.id}
      />
    {/each}
    {#if hasMore}
      <button class="btn-load-more" onclick={loadMore} disabled={loading}>
        {loading ? 'Loading...' : 'Load more'}
      </button>
    {/if}
  </div>
</div>

// widget/src/widgets/comments/Comments.tsx
import { useEffect, useState } from 'react'
import CommentItem from './CommentItem'
import { useToast } from './useToast'
import type { Comment, NewComment, CommentsResponse } from './types'
import styles from './comments.css?inline'

interface Props {
  widgetKey: string
  pageUrl: string
}

export default function Comments({ widgetKey, pageUrl }: Props) {
  const [comments, setComments] = useState<Comment[]>([])
  const [hasMore, setHasMore] = useState(false)
  const [loading, setLoading] = useState(false)
  const [body, setBody] = useState('')
  const [total, setTotal] = useState(0)
  const [pinnedCommentId, setPinnedCommentId] = useState<string | null>(null)
  const { message, fading, show } = useToast()

  const fetchComments = async (cursor?: string) => {
    setLoading(true)
    const url = `${import.meta.env.VITE_API_URL}/comments?widget_key=${widgetKey}&page_url=${encodeURIComponent(pageUrl)}${cursor ? `&cursor=${cursor}` : ''}`
    const data: CommentsResponse = await fetch(url).then(res => res.json())
    setComments(prev => cursor ? [...prev, ...data.comments] : data.comments)
    setHasMore(data.hasMore)
    setTotal(data.total ?? (cursor ? total : data.comments.length))
    if (!cursor) setPinnedCommentId(data.pinnedCommentId)
    setLoading(false)
  }

  useEffect(() => { fetchComments() }, [])

  const loadMore = () => {
    const lastComment = comments[comments.length - 1]
    if (lastComment) fetchComments(lastComment.id)
  }

  const postComment = async () => {
    if (!body.trim()) return

    const res = await fetch(`${import.meta.env.VITE_API_URL}/comments`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ widget_key: widgetKey, page_url: pageUrl, body }),
    })

    const data: NewComment = await res.json()

    if (!res.ok) {
      show((data as any).error || 'Failed to post comment')
      return
    }

    setBody('')

    if (data.status === 'approved') {
      setComments(prev => [{ ...data, replies: [] }, ...prev])
      setTotal(prev => prev + 1)
      show('Comment posted!')
    } else {
      show('Your comment has been submitted and is awaiting approval.')
    }
  }

  return (
    <>
      <style>{styles}</style>
      <div className="widget">
        <h3>{total} {total === 1 ? 'Comment' : 'Comments'}</h3>
        <div className="input-area">
          <textarea
            value={body}
            onChange={e => setBody(e.target.value)}
            maxLength={1000}
            placeholder="Add a comment..."
          />
          <div className="input-actions">
            <span className="char-count">{body.length}/1000</span>
            <button className="btn-post" onClick={postComment} disabled={!body.trim()}>
              Post
            </button>
          </div>
        </div>
        {message && (
          <div className={`toast ${fading ? 'toast-fade-out' : ''}`}>{message}</div>
        )}
        <div className="comments-list">
          {comments.length === 0 && !loading && (
            <p className="empty">No comments yet. Be the first!</p>
          )}
          {comments.map(c => (
            <CommentItem
              key={c.id}
              comment={c}
              widgetKey={widgetKey}
              pageUrl={pageUrl}
              isPinned={pinnedCommentId === c.id}
            />
          ))}
          {hasMore && (
            <button className="btn-load-more" onClick={loadMore} disabled={loading}>
              {loading ? 'Loading...' : 'Load more'}
            </button>
          )}
        </div>
      </div>
    </>
  )
}
